import { WeatherDataProps } from "../types";

export const locationArray: WeatherDataProps[] = [
  {
    stationId: 1,
    name: "Alpha",
    type: "Automatic Weather Station",
    location: "Pto. Rivas Ibaba, Balanga City, Bataan",
    coordinates: [120.5566, 14.6907],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Processed_seafood_clipped.jpg/1280px-Processed_seafood_clipped.jpg",
    temp: 20,
    heatIndex: 30,
    humidity: 40,
    precip: 100,
    airPressure: 1000,
    gust: 10,
    windSpeed: 4.61,
    windDirection: 75,
    uvIndex: 1,
    irradiance: 40000,
    lightIntensity: 5400,
    battery: 90,
    status: "Active",
  },
  {
    stationId: 2,
    name: "Beta",
    type: "Automatic Weather Station",
    location: "Pag-asa, Bagac, Bataan",
    coordinates: [120.3892, 14.5933],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/BRP_Jose_Rizal_at_RIMPAC_2020_005.jpg/1280px-BRP_Jose_Rizal_at_RIMPAC_2020_005.jpg",
    temp: 30,
    heatIndex: 37,
    humidity: 25,
    precip: 508,
    airPressure: 2034,
    gust: 14,
    windSpeed: 4.61,
    windDirection: 100.5,
    uvIndex: 1,
    irradiance: 40000,
    lightIntensity: 5400,
    battery: 35,
    status: "Active",
  },
  {
    stationId: 3,
    name: "Cupcake",
    type: "Automatic Weather Station",
    location: "Sisiman, Mariveles, Bataan",
    coordinates: [120.5177, 14.4273],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/c/cd/Carabao.jpg",
    temp: 24,
    heatIndex: 63,
    humidity: 9,
    precip: 50,
    airPressure: 231,
    gust: 24,
    windSpeed: 3.2,
    windDirection: 360,
    uvIndex: 3,
    irradiance: 400,
    lightIntensity: 500,
    battery: 25,
    status: "Inactive",
  },
  {
    stationId: 4,
    name: "Donut",
    type: "Automatic Weather Station",
    location: "Bayan-bayanan, Dinalupihan, Bataan",
    coordinates: [120.4474, 14.8643],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Core_Value.JPG/1280px-Core_Value.JPG",
    temp: 60,
    heatIndex: 65,
    humidity: 30,
    precip: 948,
    airPressure: 1234,
    gust: 35,
    windSpeed: 534.2,
    windDirection: 270,
    uvIndex: 1,
    irradiance: 40000,
    lightIntensity: 5400,
    battery: 69,
    status: "Active",
  },

  {
    stationId: 5,
    name: "Eclair",
    type: "Automatic Weather Station",
    location: "Townsite, Limay, Bataan",
    coordinates: [120.5912, 14.5553],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/St._Agustine_Paoay_Church_02.jpg/1280px-St._Agustine_Paoay_Church_02.jpg",
    temp: 153,
    heatIndex: 234,
    humidity: 2352,
    precip: 2345,
    airPressure: 62341,
    gust: 560,
    windSpeed: 342.234,
    windDirection: 180,
    uvIndex: 1,
    irradiance: 40000,
    lightIntensity: 5400,
    battery: 78,
    status: "Active",
  },
  {
    stationId: 6,
    name: "Foxtrot",
    type: "Automatic Weather Station",
    location: "Abucay, Bataan",
    coordinates: [120.51655749421144, 14.722171591112968],
    imgStation:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Processed_seafood_clipped.jpg/1280px-Processed_seafood_clipped.jpg",
    temp: 20,
    heatIndex: 30,
    humidity: 40,
    precip: 100,
    airPressure: 1000,
    gust: 3802,
    windSpeed: 4.61,
    windDirection: 75,
    uvIndex: 1,
    irradiance: 40000,
    lightIntensity: 5400,
    battery: 56,
    status: "Inactive",
  },
];

export const styles = [
  {
    title: "Dark",
    uri: "mapbox://styles/mapbox/dark-v11",
  },
  {
    title: "Light",
    uri: "mapbox://styles/mapbox/light-v11",
  },
  {
    title: "Day",
    uri: "mapbox://styles/mapbox/navigation-day-v1",
  },
  {
    title: "Night",
    uri: "mapbox://styles/mapbox/navigation-night-v1",
  },
  {
    title: "Satellite",
    uri: "mapbox://styles/mapbox/satellite-streets-v11",
  },
  {
    title: "Streets",
    uri: "mapbox://styles/mapbox/streets-v11",
  },
];
